export const REGIONS = [
  {
    id: 'africa',
    name: 'Africa',
    color: '#9a603e',
    short: 'AF',
    subregions: ['North Africa', 'West Africa', 'East Africa', 'Central & Southern Africa'],
  },
  {
    id: 'west-asia',
    name: 'West Asia',
    color: '#ac793c',
    short: 'WA',
    subregions: ['Mesopotamia', 'Anatolia', 'Levant', 'Iran & Arabia'],
  },
  {
    id: 'europe',
    name: 'Europe',
    color: '#537765',
    short: 'EU',
    subregions: ['Mediterranean', 'Northern Europe', 'Western Europe', 'Eastern Europe'],
  },
  {
    id: 'south-asia',
    name: 'South Asia',
    color: '#9c5b53',
    short: 'SA',
    subregions: ['Indus region', 'Indian subcontinent', 'Sri Lanka', 'Himalayas'],
  },
  {
    id: 'east-asia',
    name: 'East Asia',
    color: '#6079a0',
    short: 'EA',
    subregions: ['China', 'Korea', 'Japan'],
  },
  {
    id: 'central-asia',
    name: 'Central & North Asia',
    color: '#877451',
    short: 'CA',
    subregions: ['Central Asia', 'Steppe', 'Siberia'],
  },
  {
    id: 'southeast-asia',
    name: 'Southeast Asia',
    color: '#618779',
    short: 'SE',
    subregions: ['Mainland Southeast Asia', 'Maritime Southeast Asia'],
  },
  {
    id: 'americas',
    name: 'The Americas',
    color: '#8a7297',
    short: 'AM',
    subregions: ['North America', 'Mesoamerica', 'Caribbean', 'South America'],
  },
  {
    id: 'oceania',
    name: 'Oceania',
    color: '#4f8898',
    short: 'OC',
    subregions: ['Australia', 'New Guinea', 'Pacific Islands', 'Aotearoa New Zealand'],
  },
  {
    id: 'global',
    name: 'Across the world',
    color: '#707772',
    short: 'GL',
    subregions: ['Cross-regional'],
  },
] as const
export const THEMES = [
  { id: 'society', name: 'People & society' },
  { id: 'politics', name: 'Power & politics' },
  { id: 'exchange', name: 'Trade & exchange' },
  { id: 'knowledge', name: 'Science & knowledge' },
  { id: 'belief', name: 'Belief & philosophy' },
  { id: 'arts', name: 'Art & expression' },
  { id: 'environment', name: 'Land & environment' },
  { id: 'health', name: 'Health & wellbeing' },
  { id: 'rights', name: 'Rights & resistance' },
] as const
export const PRESETS = [
  {
    id: 'whole',
    title: 'All human history',
    from: '300000BCE',
    to: '2026CE',
    caption: 'Deep time, many perspectives',
  },
  {
    id: '1200',
    title: 'Around 1200 CE',
    from: '1000CE',
    to: '1400CE',
    caption: 'Cities, exchange & connected worlds',
  },
  {
    id: 'early',
    title: 'The first cities',
    from: '4000BCE',
    to: '1000BCE',
    caption: 'Different paths to urban life',
  },
  {
    id: 'classical',
    title: 'Empires & ideas',
    from: '800BCE',
    to: '600CE',
    caption: 'Institutions, knowledge & belief',
  },
  {
    id: 'connected',
    title: 'Oceanic connections',
    from: '1400CE',
    to: '1800CE',
    caption: 'Encounter, conquest & resistance',
  },
  {
    id: 'modern',
    title: 'A changing world',
    from: '1750CE',
    to: '2026CE',
    caption: 'Revolutions, rights & technology',
  },
  {
    id: 'agriculture',
    title: 'Agriculture & settlement',
    from: '12000BCE',
    to: '3000BCE',
    caption: 'Land, food & communities',
  },
  {
    id: 'prehistory',
    title: 'Deep human history',
    from: '300000BCE',
    to: '10000BCE',
    caption: 'Explore beyond the written record',
  },
]
export const regionName = (id: string) => REGIONS.find((r) => r.id === id)?.name || id
