/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys.$journeyId'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/downloads': typeof DownloadsRoute
  '/offline': typeof OfflineRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/downloads': typeof DownloadsRoute
  '/offline': typeof OfflineRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/downloads': typeof DownloadsRoute
  '/offline': typeof OfflineRoute
  '/search': typeof SearchRoute
  '/timeline': typeof TimelineRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/downloads'
    | '/offline'
    | '/search'
    | '/timeline'
    | '/entities/$entityId'
    | '/events/$eventId'
    | '/journeys/$journeyId'
    | '/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/downloads'
    | '/offline'
    | '/search'
    | '/timeline'
    | '/entities/$entityId'
    | '/events/$eventId'
    | '/journeys/$journeyId'
    | '/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/downloads'
    | '/offline'
    | '/search'
    | '/timeline'
    | '/entities/$entityId'
    | '/events/$eventId'
    | '/journeys/$journeyId'
    | '/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  DownloadsRoute: typeof DownloadsRoute
  OfflineRoute: typeof OfflineRoute
  SearchRoute: typeof SearchRoute
  TimelineRoute: typeof TimelineRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  DownloadsRoute: DownloadsRoute,
  OfflineRoute: OfflineRoute,
  SearchRoute: SearchRoute,
  TimelineRoute: TimelineRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
